name: my_blog_app
description: A simple offline blogging app using Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
